server:
  port: 8080
spring:
  application:
    name: bff-innovatech
services:
  proyectos:
    url: ${SERVICES_PROYECTOS_URL:http://localhost:8081}
  recursos:
    url: ${SERVICES_RECURSOS_URL:http://localhost:8082}
